from django.conf.urls import url

from . import views, views_admin

urlpatterns = [   
    url(r'^$', views.index, name='index'),
    url(r'^form/$', views.form, name='form'),
    url(r'^pages/$', views.pages, name='pages'),
    url(r'^pages/filter=(?P<tag>[\w ]+)/$', views.filter_pages, name='filter_pages'),
    url(r'^pages/(?P<page_name>[\w.]+)/$', views.page, name='page'),
    url(r'^pages/(?P<page_name>[\w.]+)/del_comment/id=(?P<id>[0-9]+)/$', views.del_comment, name='del_comment'),
    url(r'^mailbox/$', views.mailbox, name='mailbox'),
    url(r'^mailbox/received/$', views.mailbox_received, name='mailbox_received'),
    url(r'^mailbox/received/search=(?P<username>[\w.-_]+)/$', views.mailbox_received_search, name='mailbox_received_search'),
    url(r'^mailbox/sent/$', views.mailbox_sent, name='mailbox_sent'),
    url(r'^mailbox/sent/search=(?P<username>[\w.-_]+)/$', views.mailbox_sent_search, name='mailbox_sent_search'),
    url(r'^mailbox/del/id=(?P<id>[0-9]+)$', views.mailbox_del, name='mailbox_del'),
    url(r'^mailbox/send/$', views.mailbox_send, name='mailbox_send'),
    url(r'^mailbox/send/to=(?P<to>[\w.-_]+)/$', views.mailbox_send_to, name='mailbox_send_to'),
    url(r'^thx/name=(?P<name>[\w ]+)/$', views.thx, name='thx'),   
    url(r'^rss.xml', views.rss, name='rss'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/(?P<username>[\w.-_]+)/change_group/$', views.change_group, name='change_group'),
    url(r'^profile/(?P<username>[\w.-_]+)/$', views.profile, name='profile'),
    url(r'^edit_profile/(?P<username>[\w.-_]+)/$', views.edit_profile, name='edit_profile'),
    url(r'^edit_profile/(?P<username>[\w.-_]+)/del_pic', views.del_pic, name='del_pic'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^no_access/$', views.no_access, name='no_access'),
    url(r'^admin/$', views_admin.admin_index, name='admin_index'),
    url(r'^admin/messages/$', views_admin.admin_messages_index, name='admin_messages_index'),
    url(r'^admin/messages/page=(?P<page>[0-9]+)/$', views_admin.admin_messages, name='admin_messages'),
    url(r'^admin/messages/sort_by=(?P<sort_by>[a-z_]+)&order=(?P<order>[a-z]+)/(?P<page>[0-9]+)/$', views_admin.admin_messages_sort, name='admin_messages_sort'),
    url(r'^admin/messages/form', views_admin.messages_form, name='messages_form'),
    url(r'^admin/messages/answer', views_admin.messages_answer, name='messages_answer'),
    url(r'^admin/messages/del_selected', views_admin.messages_del_selected, name='messages_del_selected'),
    url(r'^admin/pages/$', views_admin.admin_pages, name='admin_pages'),
    url(r'^admin/pages/change_status/(?P<page_order>[0-9]+)/$', views_admin.change_status, name='change_status'),
    url(r'^admin/pages/sort_by=(?P<sort_by>[a-z_]+)&order=(?P<order>[a-z]+)', views_admin.sort_pages, name='sort_pages'),
    url(r'^admin/pages/del_selected', views_admin.pages_del_selected, name='pages_del_selected'),
    url(r'^admin/pages/add', views_admin.add_page, name='add_page'),
    url(r'^admin/pages/edit/page_order=(?P<page_order>[0-9]+)', views_admin.pages_edit, name='pages_edit'),
    url(r'^admin/pages/delete/(?P<page_order>[0-9]+)', views_admin.pages_delete, name='pages_delete'),
    url(r'^admin/questions/$', views_admin.admin_questions, name='admin_questions'),
    url(r'^admin/questions/add', views_admin.add_question, name='add_question'),
    url(r'^admin/questions/delete/id=(?P<id>[0-9]+)', views_admin.del_question, name='del_question')
]